kind: Service
apiVersion: v1
metadata:
  name: myfirstdevopsservice
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      # Port to forward to inside the pod
      targetPort: 80
  type: LoadBalancer
